const express = require('express');
const router = express.Router();
const { auth } = require('../middleware/auth');
const OpenAI = require('openai');

const Consultation = require('../models/Consultation');
const Patient = require('../models/Patient');
const Doctor = require('../models/Doctor');

// 🔁 OpenRouter Client
const openai = new OpenAI({
  apiKey: process.env.OPENROUTER_API_KEY,
  baseURL: 'https://openrouter.ai/api/v1',
});

router.post('/consultation-report', auth, async (req, res) => {
  try {
    const { consultation, appointment } = req.body;

    // 🔐 Fetch consultation
    const dbConsultation = await Consultation.findById(consultation._id);
    if (!dbConsultation) {
      return res.status(404).json({ message: 'Consultation not found' });
    }

    // ✅ Return cached AI report
    if (dbConsultation.aiReport) {
      return res.json({
        report: dbConsultation.aiReport,
        fromCache: true,
      });
    }

    // 👤 Patient
    const patient = await Patient.findById(appointment.patientId);
    if (!patient) {
      return res.status(404).json({ message: 'Patient not found' });
    }

    // 🧑‍⚕️ Doctor
    const doctor = await Doctor.findById(appointment.doctorId);
    if (!doctor) {
      return res.status(404).json({ message: 'Doctor not found' });
    }

    // 🧠 Prompt
const prompt = `
You are a professional medical assistant AI.
Generate a structured medical consultation report.

IMPORTANT RULES:
- Do NOT include today's date, report generation date, or timestamps.
- Do NOT include doctor signatures, patient signatures, or sign-off lines.
- Do NOT add "Generated by AI" or any footer text.
- End the report strictly after the "Follow-up Recommendation" section.

PATIENT DETAILS
Name: ${patient.firstName} ${patient.lastName}
Date of Birth: ${patient.dateOfBirth}
Phone: ${patient.phone}
Medical History: ${patient.medicalHistory?.join(', ') || 'None'}

DOCTOR DETAILS
Name: ${doctor.firstName} ${doctor.lastName}
Specialty: ${appointment.specialty}

CONSULTATION DETAILS
Status: ${consultation.status}
Appointment Date: ${appointment.appointmentDate}

CHAT MESSAGES
${consultation.chatMessages.map(
  m => `- ${m.senderRole}: ${m.message}`
).join('\n')}

TRANSCRIPTION
${consultation.transcription.map(
  t => `${t.speaker}: ${t.text}`
).join('\n')}

Generate the report with ONLY the following sections:
1. Consultation Summary
2. Key Symptoms
3. Doctor Observations
4. Advice / Treatment
5. Follow-up Recommendation
`;


    // 🤖 OpenRouter AI Call
    const completion = await openai.chat.completions.create({
      model: 'openai/gpt-4o-mini', // fast + cost-effective
      messages: [
        { role: 'system', content: 'You are a medical documentation assistant.' },
        { role: 'user', content: prompt },
      ],
      temperature: 0.3,
    });

    const reportText = completion.choices[0].message.content;

    // 💾 Save once
    dbConsultation.aiReport = reportText;
    await dbConsultation.save();

    res.json({
      report: reportText,
      fromCache: false,
    });
  } catch (error) {
    console.error(error);
    res.status(500).json({
      message: 'AI report generation failed',
      error: error.message,
    });
  }
});

module.exports = router;
